import sqlalchemy as sa
from sqlalchemy.orm import relationship
from .db import Base
from datetime import datetime


class Material(Base):
    __tablename__ = "materials"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "mat_xxx"
    type = sa.Column(sa.String, nullable=False)  # text,pdf,doc,docx,file
    status = sa.Column(sa.String, nullable=False, default="available")

    # keep bytes out of DB, stays NULL.
    storage_url = sa.Column(sa.String, nullable=True)

    # JSON string with structured metadata
    metadata_json = sa.Column(sa.Text, nullable=True)

    filename = sa.Column(sa.String, nullable=True)
    mime = sa.Column(sa.String, nullable=True)
    sizebyte = sa.Column(sa.Integer, nullable=True)
    contentbytes = sa.Column(sa.LargeBinary, nullable=True)

    # Creation timestamp generated by DB.
    created = sa.Column(sa.DateTime(timezone=True), server_default=sa.func.now())


# New: User model
class User(Base):
    __tablename__ = "users"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "user_xxx"
    email = sa.Column(sa.String, unique=True, nullable=False, index=True)
    username = sa.Column(sa.String, unique=True, nullable=False, index=True)
    password_hash = sa.Column(sa.String, nullable=False)  # Argon2id password hash

    # Timestamps
    created_at = sa.Column(sa.DateTime, default=datetime.utcnow)
    last_login = sa.Column(sa.DateTime, nullable=True)

    # Relationship to frameworks
    frameworks = relationship(
        "Framework", back_populates="creator", cascade="all, delete-orphan"
    )


# New: Framework model
class Framework(Base):
    __tablename__ = "frameworks"

    id = sa.Column(sa.String, primary_key=True, index=True)  # e.g. "fw_xxx"
    title = sa.Column(sa.String, nullable=False)
    version = sa.Column(sa.String, default="1.0.0")
    family = sa.Column(
        sa.String, nullable=False, index=True
    )  # Group name (AI auto-assigned)
    confidence = sa.Column(
        sa.Float, default=0.0
    )  # 0-100 (currently mock, future AI-calculated)
    pov = sa.Column(sa.String, nullable=True)

    # User relationship
    creator_id = sa.Column(
        sa.String, sa.ForeignKey("users.id"), nullable=False, index=True
    )
    creator = relationship("User", back_populates="frameworks")

    # Framework content stored as JSON strings
    # Designed this way for flexibility to avoid frequent DB schema changes
    metadata_json = sa.Column(
        sa.Text, nullable=False
    )  # {title, version, tags, lastUpdated}
    steps_json = sa.Column(
        sa.Text, nullable=False
    )  # [{id, name, description, subSteps}]
    artefacts_json = sa.Column(
        sa.Text, nullable=False
    )  # {default: {...}, additional: [...]}
    risks_json = sa.Column(sa.Text, nullable=False)  # [{id, title, description}]
    escalation_json = sa.Column(sa.Text, nullable=False)  # [{id, trigger, action}]

    # Raw LLM output (for debugging and future improvements)
    raw_framework_json = sa.Column(sa.Text, nullable=True)  # Full AI response
    raw_metadata_json = sa.Column(
        sa.Text, nullable=True
    )  # Metadata extracted by local LLM

    # Timestamps
    created_at = sa.Column(sa.DateTime, default=datetime.utcnow, index=True)
    updated_at = sa.Column(
        sa.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )


# Preset Framework Groups (AI selects from these)
FRAMEWORK_GROUPS = [
    "Financial",  # Finance, accounting, investment
    "Healthcare",  # Medical, health
    "Legal",  # Law, compliance
    "Technology",  # Tech, IT, software
    "Education",  # Education, training
    "Marketing",  # Marketing, advertising
    "Operations",  # Operations, processes
    "Human Resources",  # HR
    "Sales",  # Sales
    "Other",  # Other (fallback category)
]


class SyncedVectorItem(Base):
    __tablename__ = "synced_vector_items"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    doc_id = sa.Column(sa.String, nullable=False, index=True)
    vs_id = sa.Column(sa.String, nullable=False, index=True)
    source = sa.Column(sa.String, nullable=True)
    first_synced_at = sa.Column(sa.DateTime, default=datetime.utcnow)
    last_synced_at = sa.Column(
        sa.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    __table_args__ = (sa.UniqueConstraint("doc_id", "vs_id", name="uix_doc_vs"),)
